"""filetable

Revision ID: 4dff5b1f9d93
Revises: bfe6213c65f8
Create Date: 2025-09-25 11:26:35.038576

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '4dff5b1f9d93'
down_revision: Union[str, Sequence[str], None] = 'bfe6213c65f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fdfs_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('taltol_page', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('taskresults', sa.Column('post_date', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('taskresults', sa.Column('finally_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('taskresults', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_column('taskresults', 'data_status')
    op.add_column('tasks', sa.Column('phase', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('tasks', 'status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('tasks', 'phase')
    op.add_column('taskresults', sa.Column('data_status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('taskresults', 'status')
    op.drop_column('taskresults', 'finally_data')
    op.drop_column('taskresults', 'post_date')
    op.drop_table('file')
    # ### end Alembic commands ###
