"""fix extracted_data 

Revision ID: dc1f9494b3b5
Revises: e1c6205d9eee
Create Date: 2025-08-27 14:48:21.292503

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc1f9494b3b5'
down_revision: Union[str, Sequence[str], None] = 'e1c6205d9eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskresults', 'extracted_data',
               existing_type=sa.INTEGER(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('taskresults', 'data_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskresults', 'data_status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('taskresults', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
