"""delete uuid 

Revision ID: e1c6205d9eee
Revises: 6f0ad23c237e
Create Date: 2025-08-27 14:40:42.323884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c6205d9eee'
down_revision: Union[str, Sequence[str], None] = '6f0ad23c237e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_uuid_key'), 'tasks', type_='unique')
    op.drop_column('tasks', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tasks_uuid_key'), 'tasks', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
