"""更改模任务表

Revision ID: 1c2303c01e26
Revises: 46298c994d6e
Create Date: 2024-05-07 18:50:26.445264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2303c01e26'
down_revision: Union[str, None] = '46298c994d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('ori_file_id', sa.Integer(), nullable=True, comment='原始文件id 只在子任务中记录'))
    op.add_column('task', sa.Column('file_id', sa.Integer(), nullable=True, comment='输入文件id 只在子任务中记录'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'file_id')
    op.drop_column('task', 'ori_file_id')
    # ### end Alembic commands ###
