"""更改模型场景关系

Revision ID: 46298c994d6e
Revises: 
Create Date: 2024-04-26 14:46:49.632590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46298c994d6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ele_value', 'task_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ele_value', 'file_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ele_value', 'element_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('ele_value_ibfk_5', 'ele_value', type_='foreignkey')
    op.drop_constraint('ele_value_ibfk_1', 'ele_value', type_='foreignkey')
    op.drop_constraint('ele_value_ibfk_4', 'ele_value', type_='foreignkey')
    op.drop_constraint('ele_value_ibfk_3', 'ele_value', type_='foreignkey')
    op.create_foreign_key(None, 'ele_value', 'ele_value', ['ele_value_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ele_value', 'file', ['file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ele_value', 'task', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ele_value', 'element', ['element_id'], ['id'], ondelete='SET NULL')
    op.alter_column('element', 'scene_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('element_ibfk_3', 'element', type_='foreignkey')
    op.create_foreign_key(None, 'element', 'scene', ['scene_id'], ['id'], ondelete='SET NULL')
    op.alter_column('msg_task', 'file_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('msg_task_ibfk_2', 'msg_task', type_='foreignkey')
    op.create_foreign_key(None, 'msg_task', 'file', ['file_id'], ['id'], ondelete='SET NULL')
    op.alter_column('post_process', 'element_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'post_process', 'element', ['element_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('scene_model_association_ibfk_2', 'scene_model_association', type_='foreignkey')
    op.drop_constraint('scene_model_association_ibfk_1', 'scene_model_association', type_='foreignkey')
    op.create_foreign_key(None, 'scene_model_association', 'scene', ['scene_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scene_model_association', 'model_info', ['model_info_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_ibfk_2', 'task', type_='foreignkey')
    op.drop_constraint('task_ibfk_3', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'scene', ['scene_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('user_scene_association_ibfk_1', 'user_scene_association', type_='foreignkey')
    op.drop_constraint('user_scene_association_ibfk_2', 'user_scene_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_scene_association', 'user', ['user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_scene_association', 'scene', ['scene'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_scene_association', type_='foreignkey')
    op.drop_constraint(None, 'user_scene_association', type_='foreignkey')
    op.create_foreign_key('user_scene_association_ibfk_2', 'user_scene_association', 'user', ['user'], ['id'])
    op.create_foreign_key('user_scene_association_ibfk_1', 'user_scene_association', 'scene', ['scene'], ['id'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_3', 'task', 'user', ['user_id'], ['id'])
    op.create_foreign_key('task_ibfk_2', 'task', 'scene', ['scene_id'], ['id'])
    op.drop_constraint(None, 'scene_model_association', type_='foreignkey')
    op.drop_constraint(None, 'scene_model_association', type_='foreignkey')
    op.create_foreign_key('scene_model_association_ibfk_1', 'scene_model_association', 'model_info', ['model_info_id'], ['id'])
    op.create_foreign_key('scene_model_association_ibfk_2', 'scene_model_association', 'scene', ['scene_id'], ['id'])
    op.drop_constraint(None, 'post_process', type_='foreignkey')
    op.alter_column('post_process', 'element_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'msg_task', type_='foreignkey')
    op.create_foreign_key('msg_task_ibfk_2', 'msg_task', 'file', ['file_id'], ['id'])
    op.alter_column('msg_task', 'file_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'element', type_='foreignkey')
    op.create_foreign_key('element_ibfk_3', 'element', 'scene', ['scene_id'], ['id'])
    op.alter_column('element', 'scene_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'ele_value', type_='foreignkey')
    op.drop_constraint(None, 'ele_value', type_='foreignkey')
    op.drop_constraint(None, 'ele_value', type_='foreignkey')
    op.drop_constraint(None, 'ele_value', type_='foreignkey')
    op.create_foreign_key('ele_value_ibfk_3', 'ele_value', 'element', ['element_id'], ['id'])
    op.create_foreign_key('ele_value_ibfk_4', 'ele_value', 'ele_value', ['ele_value_id'], ['id'])
    op.create_foreign_key('ele_value_ibfk_1', 'ele_value', 'task', ['task_id'], ['id'])
    op.create_foreign_key('ele_value_ibfk_5', 'ele_value', 'file', ['file_id'], ['id'])
    op.alter_column('ele_value', 'element_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ele_value', 'file_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ele_value', 'task_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
